# Generated by Django 4.1.7 on 2023-03-29 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_user_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.CharField(default='noimg', max_length=254),
            preserve_default=False,
        ),
    ]
