# Generated by Django 4.1.7 on 2023-03-30 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_conversation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='convo',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
