# Generated by Django 4.1.7 on 2023-03-31 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_conversation_convo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, max_length=50)),
                ('convo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_instance', to='base.conversation')),
            ],
        ),
    ]
